from itertools import product


class QuestionnaireEnums:

    satisfaction = ["-",
                    "4 - Oui, tout à fait Thierry",
                    "3 - Oui, plutôt",
                    "2 - Bof, pas trop, non",
                    "1 - Pas du tout camarade"]

    count = ["-",
             "0",
             "1 - 4",
             "5 - 9",
             "10 - 19",
             "20 - 29",
             "30 - 49",
             "50 - 99",
             "100+"]

    timing = ["-",
              "moins d'un jour",
              "moins de 3 jours",
              "moins d'une semaine",
              "moins de deux semaines",
              "moins d'un mois",
              "moins de 3 mois",
              "moins de 6 mois",
              "moins d'un an",
              "plus d'un an"]

    device_type = ["Smartphone", "Tablette", "PC"]

    @staticmethod
    def choices(item):
        return [(i, i) for i in QuestionnaireEnums.__dict__.get(item)]


class MainEnums:
    questionnaire = QuestionnaireEnums


COUNTRY_LIST = ['Afghanistan', 'Afrique du Sud', 'Albanie',
                'Algérie', 'Allemagne', 'Andorre', 'Angola',
                'Antigua-et-Barbuda', 'Arabie saoudite',
                'Argentine', 'Arménie', 'Australie', 'Autriche',
                'Azerbaïdjan', 'Bahamas', 'Bahreïn', 'Bangladesh',
                'Barbade', 'Belgique', 'Belize', 'Bhoutan', 'Birmanie',
                'Biélorussie', 'Bolivie', 'Bosnie-Herzégovine', 'Botswana',
                'Brunei', 'Brésil', 'Bulgarie', 'Burkina Faso', 'Burundi',
                'Bénin', 'Cambodge', 'Cameroun', 'Canada', 'Cap-Vert',
                'Chili', 'Chine', 'Chypre', 'Colombie', 'Comores',
                'Corée du Nord', 'Corée du Sud', 'Costa Rica', 'Croatie',
                'Cuba', "Côte d'Ivoire", 'Danemark', 'Djibouti',
                'Dominique', 'Egypte', 'Emirats arabes unis', 'Equateur',
                'Erythrée', 'Espagne', 'Estonie', 'Etats-Unis',
                'Ethiopie', 'Fidji', 'Finlande', 'France', 'Gabon',
                'Gambie', 'Ghana', 'Grenade', 'Grèce', 'Guatemala',
                'Guinée', 'Guinée équatoriale', 'Guinée-Bissau',
                'Guyana', 'Géorgie', 'Haïti', 'Honduras', 'Hongrie',
                'Iles Cook', 'Iles Marshall', 'Iles Salomon', 'Inde',
                'Indonésie', 'Irak', 'Iran', 'Irlande', 'Islande',
                'Israël', 'Italie', 'Jamaïque', 'Japon', 'Jordanie',
                'Kazakhstan', 'Kenya', 'Kirghizistan', 'Kiribati',
                'Koweït', 'Laos', 'Lesotho', 'Lettonie', 'Liban',
                'Liberia', 'Libye', 'Liechtenstein', 'Lituanie',
                'Luxembourg', 'Macédoine du Nord', 'Madagascar',
                'Malaisie', 'Malawi', 'Maldives', 'Mali', 'Malte',
                'Maroc', 'Maurice', 'Mauritanie', 'Mexique',
                'Micronésie', 'Moldavie', 'Monaco', 'Mongolie',
                'Monténégro', 'Mozambique', 'Namibie', 'Nauru',
                'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norvège',
                'Nouvelle-Zélande', 'Népal', 'Oman', 'Ouganda', 'Ouzbékistan',
                'Pakistan', 'Palaos', 'Palestine', 'Panamá',
                'Papouasie-Nouvelle-Guinée', 'Paraguay', 'Pays-Bas',
                'Philippines', 'Pologne', 'Portugal', 'Pérou', 'Qatar',
                'Roumanie', 'Royaume-Uni', 'Russie', 'Rwanda',
                'République centrafricaine', 'République dominicaine',
                'République du Congo', 'République démocratique du Congo',
                'République tchèque', 'Saint-Christophe-et-Niévès',
                'Saint-Marin', 'Saint-Vincent-et-les Grenadines',
                'Sainte-Lucie', 'Salvador', 'Samoa', 'Serbie',
                'Seychelles', 'Sierra Leone', 'Singapour', 'Slovaquie',
                'Slovénie', 'Somalie', 'Soudan', 'Soudan du Sud',
                'Sri Lanka', 'Suisse', 'Suriname', 'Suède', 'Swaziland',
                'Syrie', 'São Tomé-et-Principe', 'Sénégal', 'Tadjikistan',
                'Tanzanie', 'Tchad', 'Thaïlande', 'Timor oriental',
                'Togo', 'Tonga', 'Trinité-et-Tobago', 'Tunisie',
                'Turkménistan', 'Turquie', 'Tuvalu', 'Ukraine',
                'Uruguay', 'Vanuatu', 'Vatican', 'Venezuela',
                'Viêt Nam', 'Yémen', 'Zambie', 'Zimbabwe', 'Égypte',
                'Émirats arabes unis', 'Équateur', 'Érythrée',
                'États-Unis', 'Éthiopie']


TOWN_LIST = ['Abbeville', 'Agen', 'Aix-en-Provence', 'Aix-les-Bains', 'Ajaccio',
             'Albertville', 'Albi', 'Alençon', 'Alfortville', 'Altkirch ',
             'Alès', 'Ambert', 'Amiens', 'Angers', 'Anglet', 'Angoulême',
             'Annecy', 'Annemasse', 'Antibes', 'Antony', 'Apt', 'Arcachon',
             'Argelès-Gazost', 'Argentan', 'Argenteuil', 'Arles', 'Arras',
             'Asnières-sur-Seine', 'Athis-Mons', 'Aubagne', 'Aubervilliers',
             'Aubusson', 'Auch', 'Aulnay-sous-Bois', 'Aurillac', 'Autun',
             'Auxerre', 'Avallon', 'Avesnes-sur-Helpe', 'Avignon', 'Avranches',
             'Bagneux', 'Bagnolet', 'Bagnères-de-Bigorre', 'Baie-Mahault',
             'Bar-le-Duc', 'Bar-sur-Aube', 'Barcelonnette', 'Basse - Terre',
             'Basse-Terre', 'Bastia', 'Bayeux', 'Bayonne', 'Beaune', 'Beauvais',
             'Belfort', 'Bellac', 'Belley', 'Bergerac', 'Bernay', 'Besançon',
             'Biarritz', 'Blaye', 'Blois', 'Bobigny', 'Bondy', 'Bonneville',
             'Bordeaux', 'Boulogne-Billancourt', 'Boulogne-sur-Mer',
             'Bourg-en-Bresse', 'Bourges', 'Bressuire', 'Brest', 'Briançon',
             'Briey', 'Brignoles', 'Brioude', 'Brive-la-Gaillarde', 'Bron',
             'Bruay-la-Buissière', 'Béthune', 'Béziers', 'Cachan', 'Caen',
             'Cagnes-sur-Mer', 'Cahors', 'Calais', 'Caluire-et-Cuire', 'Calvi',
             'Cambrai', 'Cannes', 'Carcassonne', 'Carpentras', 'Castellane',
             'Castelsarrasin', 'Castres', 'Cayenne', 'CayenneSaint - Denis',
             'Cergy', 'Chalon-sur-Saône', 'Chambéry', 'Champigny-sur-Marne',
             'Charenton-le-Pont', 'Charleville-Mézières', 'Charolles',
             'Chartres', 'Chatou', 'Chaumont', 'Chelles', 'Cherbourg',
             'Cherbourg-en-Cotentin', 'Chinon', 'Choisy-le-Roi', 'Cholet',
             'Châlons-en-Champagne', 'Château-Chinon (Ville)',
             'Château-Gontier', 'Château-Thierry', 'Châteaubriant-Ancenis',
             'Châteaudun', 'Châteaulin', 'Châteauroux', 'Châtellerault',
             'Châtenay-Malabry', 'Châtillon', 'Clamart', 'Clamecy', 'Clermont',
             'Clermont-Ferrand', 'Clichy', 'Clichy-sous-Bois', 'Cognac',
             'Colmar', 'Colmar-Ribeauvillé', 'Colombes', 'Colomiers',
             'Commercy', 'Compiègne', 'Condom', 'Conflans-Sainte-Honorine',
             'Confolens', 'Corbeil-Essonnes', 'Corte', 'Cosne-Cours-sur-Loire',
             'Courbevoie', 'Coutances', 'Creil', 'Créteil', 'Céret', 'Dax',
             'Die', 'Dieppe', 'Digne-les-Bains', 'Dijon', 'Dinan', 'Dole',
             'Douai', 'Draguignan', 'Drancy', 'Dreux', 'Dumbéa', 'Dunkerque',
             'Figeac', 'Florac', 'Foix', 'Fontainebleau', 'Fontenay-le-Comte',
             'Fontenay-sous-Bois', 'Forbach-Boulay-Moselle', 'Forcalquier',
             'Fort - de - France', 'Fort-de-France', 'Fougères-Vitré',
             'Franconville', 'Fréjus', 'Gagny', 'Gap', 'Garges-lès-Gonesse',
             'Gennevilliers', 'Gex', 'Gourdon', 'Goussainville', 'Grasse',
             'Grenoble', 'Guingamp', 'Guéret', 'Haguenau',
             'Haguenau-Wissembourg', 'Houilles', 'Hyères', 'Issoire',
             'Issoudun', 'Issy-les-Moulineaux', 'Istres', 'Ivry-sur-Seine',
             'Jonzac', 'Joué-lès-Tours', 'Koungou', "L'Haÿ-les-Roses",
             'La Châtre', 'La Ciotat', 'La Courneuve', 'La Flèche',
             'La Possession', 'La Roche-sur-Yon', 'La Rochelle',
             'La Seyne-sur-Mer', 'La Tour-du-Pin', 'La Trinité', 'Langon',
             'Langres', 'Lannion', 'Laon', 'Largentière', 'Laval', 'Le Blanc',
             'Le Blanc-Mesnil', 'Le Cannet', 'Le Chesnay-Rocquencourt',
             'Le Creusot', 'Le Grand-Quevilly', 'Le Havre', 'Le Lamentin',
             'Le Mans', 'Le Marin', 'Le Perreux-sur-Marne', 'Le Port',
             'Le Puy-en-Velay', 'Le Raincy', 'Le Tampon', 'Le Vigan', 'Lens',
             'Les Abymes', 'Les Andelys', 'Les Mureaux', "Les Sables-d'Olonne",
             'Lesparre-Médoc', 'Levallois-Perret', 'Libourne', 'Lille',
             'Limoges', 'Limoux', 'Lisieux', 'Livry-Gargan', 'Liévin', 'Loches',
             'Lodève', 'Lons-le-Saunier', 'Lorient', 'Louhans', 'Lunéville',
             'Lure', 'Lyon', 'Maisons-Alfort', 'Malakoff', 'Mamers',
             'Mamoudzou', 'Mantes-la-Jolie', 'Marcq-en-Barœul', 'Marignane',
             'Marmande', 'Marseille', 'Martigues', 'Massy', 'Matoury',
             'Maubeuge', 'Mauriac', 'Mayenne', 'Meaux', 'Melun', 'Mende',
             'Metz', 'Meudon', 'Meyzieu', 'Millau', 'Mirande', 'Molsheim',
             'Mont-de-Marsan', 'Montargis', 'Montauban', 'Montbard',
             'Montbrison', 'Montbéliard', 'Montdidier',
             'Montigny-le-Bretonneux', 'Montluçon', 'Montmorillon',
             'Montpellier', 'Montreuil', 'Montrouge', 'Montélimar', 'Morlaix',
             'Mortagne-au-Perche', 'Moulins', 'Mulhouse', 'Muret', 'Mâcon',
             'Mérignac', 'Nancy', 'Nanterre', 'Nantes', 'Nantua', 'Narbonne',
             'Neufchâteau', 'Neuilly-sur-Marne', 'Neuilly-sur-Seine', 'Nevers',
             'Nice', 'Niort', 'Nogent-le-Rotrou', 'Nogent-sur-Marne',
             'Nogent-sur-Seine', 'Noisy-le-Grand', 'Noisy-le-Sec', 'Nontron',
             'Nouméa', 'Nyons', 'Nérac', 'Nîmes', 'Oloron-Sainte-Marie', 'Orly',
             'Orléans', 'Palaiseau', 'Pamiers', 'Pantin', 'Paris', 'Parthenay',
             'Pau', 'Perpignan', 'Pessac', 'Pithiviers', 'Plaisir',
             'Pointe-à-Pitre', 'Poissy', 'Poitiers', 'Pontarlier',
             'Pontault-Combault', 'Pontivy', 'Pontoise', 'Prades', 'Privas',
             'Provins', 'Puteaux', 'Périgueux', 'Péronne', 'Quimper',
             'Rambouillet', 'Redon', 'Reims', 'Rennes', 'Rethel', 'Rezé',
             'Rillieux-la-Pape', 'Riom', 'Roanne', 'Rochechouart', 'Rochefort',
             'Rodez', 'Romans-sur-Isère', 'Romorantin-Lanthenay',
             'Rosny-sous-Bois', 'Roubaix', 'Rouen', 'Rueil-Malmaison',
             'Saint-Amand-Montrond', 'Saint-André', 'Saint-Benoît',
             'Saint-Brieuc', 'Saint-Chamond', 'Saint-Claude', 'Saint-Cloud',
             'Saint-Denis', 'Saint-Dizier', 'Saint-Dié-des-Vosges',
             'Saint-Flour', 'Saint-Gaudens', 'Saint-Germain-en-Laye',
             'Saint-Girons', 'Saint-Herblain', "Saint-Jean-d'Angély",
             'Saint-Jean-de-Maurienne', 'Saint-Joseph',
             'Saint-Julien-en-Genevois', 'Saint-Laurent-du-Maroni',
             'Saint-Laurent-du-Var', 'Saint-Leu', 'Saint-Louis', 'Saint-Lô',
             'Saint-Malo', 'Saint-Martin', "Saint-Martin-d'Hères",
             'Saint-Maur-des-Fossés', 'Saint-Médard-en-Jalles', 'Saint-Nazaire',
             'Saint-Omer', 'Saint-Ouen-sur-Seine', 'Saint-Paul', 'Saint-Pierre',
             'Saint-Priest', 'Saint-Quentin', 'Saint-Raphaël', 'Saint-Étienne',
             'Saint-Étienne-du-Rouvray', 'Sainte-Geneviève-des-Bois',
             'Sainte-Marie', 'Saintes', 'Salon-de-Provence', 'Sarcelles',
             'Sarlat-la-Canéda', 'Sarrebourg-Château-Salins', 'Sarreguemines',
             'Sartrouville', 'Sartène', 'Saumur', 'Saverne',
             'Savigny-le-Temple', 'Savigny-sur-Orge', 'Schiltigheim', 'Sedan',
             'Segré', 'Senlis', 'Sens', 'Sevran', 'Six-Fours-les-Plages',
             'Soissons', 'Sotteville-lès-Rouen', 'Stains', 'Strasbourg',
             'Suresnes', 'Sète', 'Sélestat-Erstein', 'Talence', 'Tarbes',
             'Thann-Guebwiller', 'Thiers', 'Thionville', 'Thonon-les-Bains',
             'Torcy', 'Toul', 'Toulon', 'Toulouse', 'Tourcoing',
             'Tournon-sur-Rhône', 'Tours', 'Trappes', 'Tremblay-en-France',
             'Troyes', 'Tulle', 'Ussel', 'Valence', 'Valenciennes', 'Vallauris',
             'Vandœuvre-lès-Nancy', 'Vannes', 'Vaulx-en-Velin', 'Vendôme',
             'Verdun', 'Versailles', 'Vervins', 'Vesoul', 'Vichy', 'Vienne',
             'Vierzon', 'Vigneux-sur-Seine', 'Villefranche-de-Rouergue',
             'Villefranche-sur-Saône', 'Villejuif', 'Villemomble',
             "Villenave-d'Ornon", 'Villeneuve-Saint-Georges',
             "Villeneuve-d'Ascq", 'Villeneuve-sur-Lot', 'Villepinte',
             'Villeurbanne', 'Vincennes', 'Vire', 'Viry-Châtillon', 'Vitrolles',
             'Vitry-le-François', 'Vitry-sur-Seine', 'Vouziers', 'Vénissieux',
             'Wattrelos', 'Yssingeaux', 'Échirolles', 'Épernay', 'Épinal',
             'Épinay-sur-Seine', 'Étampes', 'Évreux', 'Évry',
             'Évry-Courcouronnes']

SCHOOL_LIST = ["ESC Clermont-Ferrand", "KEDGE", "NEOMA", "HEC", "ESCP-EAP"]


COMPANY_LIST = ['ABC ARBITRAGE', 'ADLPARTNER', 'ADP',
                'ADT - NOUVELLE DES ETABLISSEMENTS', 'AKKA TECHNOLOGIES',
                'ALD AUTOMOTIVE', 'ANF IMMOBILIER', 'ANOVO', 'AURES TECHNOLOGIES',
                'AXA', 'ACCORHOTELS', 'ACTEOS', 'ACTIA GROUP', 'ADVINI', 'AEDIAN',
                'AFFIPARIS', 'AFFINE', 'AFONE', 'AIR FRANCE - KLM',
                'AIR FRANCE-KLM', 'AIR LIQUIDE', 'AIRBUS', 'AIRBUS GROUP',
                'ALBIOMA', 'ALPHA MULTI ORGANOLEPTIC SYSTEM', 'ALSTOM', 'ALTAMIR',
                'ALTAMIR AMBOISE', 'ALTEN', 'ALTEN LTD', 'ALTRAN',
                'ALTRAN TECHNOLOGIES', 'AMUNDI', 'APERAM', 'APRIL', 'APRIL GROUP',
                'ARCELOR MITTAL', 'ARCELORMITTAL', 'ARCHOS', 'AREVA', 'ARGAN',
                'ARKEMA', 'ARTPRICE.COM', 'ASSYSTEM', 'AST GROUPE', 'ATARI',
                'ATOS', 'ATOS ORIGIN', 'AUBAY', 'AUCHAN HOLDING', 'AUDIKA',
                'AUFEMININ.COM', 'AUGROS COSMETIC PACKAGING', 'AUREA', 'AUSY',
                'AVANQUEST SOFTWARE', 'AVENIR FINANCE', 'AVENIR TELECOM',
                'BCI NAVIGATION', 'BNP PARIBAS', 'BPCE', 'BARBARA BUI',
                'BASTIDE LE CONFORT MÉDICAL', 'BELVEDERE', 'BENETEAU',
                'BERNARD LOISEAU', 'BIC', 'BIGBEN INTERACTIVE',
                'BIOALLIANCE PHARMA', 'BIOMERIEUX', 'BIOMÉRIEUX', 'BOIRON',
                'BOLLORÉ', 'BONDUELLE', 'BONDUELLE S.C.A.', 'BOURBON',
                'BOURSORAMA', 'BOUYGUES', 'BULL', 'BUREAU VERITAS',
                'BUSINESS & DECISION', 'BÉNÉTEAU', 'CAFOM', 'CFCAL - BANQUE',
                'CGG VERITAS', 'CIBOX INTER@CTIVE', 'CNP ASSURANCES',
                'CS COMMUNICATION & SYSTEMES', 'CAMELEON SOFTWARE', 'CANAL+',
                'CAP GEMINI', 'CAPELLI', 'CAPGEMINI', 'CARREFOUR',
                'CASINO GUICHARD', 'CASINO GUICHARD PERRACHON', 'CAST',
                'CATERING INTERNATIONAL SERVICES', 'CEGEDIM', 'CEGID GROUP',
                'CESAR', 'CHARGEURS', 'CHRISTIAN DIOR', 'CIE DES ALPES',
                'CIMENTS FRANÇAIS', 'CLAYEUX', 'CLUB MED', 'CLUB MEDITERRANEE',
                'COHERIS', 'COMPAGNIE DES ALPES', 'COTTIN FRERES',
                'CRÉDIT AGRICOLE', 'CYBERDECK', 'CYBERGUN', 'DBV TECHNOLOGIES',
                'DNXCORP', 'DALET', 'DANE - ELEC MEMORY', 'DANONE',
                'DASSAULT AVIATION', 'DASSAULT AVIATION8', 'DASSAULT SYSTÈMES',
                'DELACHAUX', 'DELTA PLUS GROUP', 'DERICHEBOURG',
                'DERICHEBOURG(EX PENAUILLE)', 'DEVOTEAM',
                'DIAGNOSTIC MEDICAL SYSTEMS', 'EBIZCUSS.COM', 'ECA', 'EDF',
                'EDF ENERGIES NOUVELLES', 'ESI GROUP', 'ESR', 'EDENRED', 'EIFFAGE',
                'ELIOR', 'ELIOR GROUP', 'ELIS', 'ENCRES DUBUIT', 'ENGIE',
                'ENTREPOSE CONTRACTING', 'ERAMET', 'ESSILOR',
                'ESSILOR INTERNATIONAL', 'ESSO FRANÇAISE', 'ETAM DEVELOPPEMENT',
                'EULER HERMES', 'EURAZEO', 'EURO DISNEY', 'EURO DISNEY SCA',
                'EURO RESSOURCES', 'EUROFINS SCIENTIFIC', 'EUROMEDIS GROUPE',
                'EURONEXT', 'EUROPACORP', 'EUROPCAR', 'EUTELSAT',
                'EXEL INDUSTRIES', 'FIPP', 'FAIVELEY TRANSPORT', 'FAURECIA',
                'FIMALAC', 'FINATIS (CASINO.ETC)', 'FLEURY MICHON', 'FNAC DARTY',
                'FONCIÈRE DES RÉGIONS', 'FRANCE TELECOM', 'FUTUREN', 'GEA',
                'GECI INTERNATIONAL', 'GFI INFORMATIQUE', 'GL EVENTS', 'GTT',
                'GUY DEGRENNE', 'GAMELOFT', 'GECINA', 'GEMALTO', 'GENERIX',
                'GENFIT', 'GROUPE ARES', 'GROUPE CARREFOUR', 'GROUPE CRIT',
                'GROUPE DIFFUSION PLUS', 'GROUPE EUROTUNNEL', 'GROUPE FLO',
                'GROUPE HIOLLE INDUSTRIES', 'GROUPE JAJ', 'GROUPE OPEN',
                'GROUPE PSA', 'GROUPE PARTOUCHE', 'GROUPE STERIA SCA',
                'GROUPE VIAL', 'GUERBET', 'GUILLEMOT CORP', 'GUYENNE ET GASCOGNE',
                'HF COMPANY', 'HAULOTTE GROUP', 'HAVAS', 'HENRI MAIRE',
                'HERMES INTERNATIONAL', 'HERMÈS INTERNATIONAL', 'HI - MEDIA',
                'HOLOGRAM INDUSTRIES', 'HUBWOO', 'IEC PROFESSIONNEL MEDIA',
                'IGE + XAO', 'IMS - INTL METAL SERVICE', 'IPSOS', 'ITS GROUP',
                'ICADE', 'ILIAD', 'IMERYS', 'INDEX MULTIMEDIA', 'INFOTEL',
                'INFOVISTA', 'INGENICO', 'INNATE PHARMA', 'INNELEC MULTIMEDIA',
                'INTER PARFUMS', 'INTERNATIONAL METAL SERVICE', 'INTERPARFUMS',
                'IPSEN', 'IT LINK', 'ITESOFT', 'JC DECAUX', 'JCDECAUX',
                'KAUFMAN & BROAD', 'KERING', 'KEYRUS', 'KINDY', 'KLEPIERRE',
                'KLÉPIERRE', 'KORIAN', "L'ORÉAL", 'LDC', 'LDLC.COM', 'LISI',
                'LVL MEDICAL GROUPE', 'LVMH', 'LA PERLA WORLD', 'LACIE', 'LACROIX',
                'LAFARGE', 'LAFUMA', 'LAGARDERE', 'LAGARDÈRE', 'LATÉCOÈRE',
                'LAURENT - PERRIER', 'LE BELIER', 'LE NOBLE AGE',
                'LE TANNEUR ET CIE', 'LECTRA', 'LEGRAND',
                'LES NOUVEAUX CONSTRUCTEURS INVESTISSEMENT', 'LEXIBOOK',
                'LINEDATA SERVICES', 'L’ORÉAL', 'M6 METROPOLE TELEVISION',
                'M6 MÉTROPOLE TÉLÉVISION', 'METABOLIC EXPLORER', 'MGI COUTIER',
                'MP NIGERIA', 'MAISONS FRANCE CONFORT', 'MAISONS DU MONDE',
                'MANITOU BF', 'MAROCAINE COMPAGNIE', 'MAUREL ET PROM', 'MECELEC',
                'MEDASYS', 'MEDIA 6', 'MEDICA', 'MEETIC', 'MEMSCAP', 'MERCIALYS',
                'MERSEN', 'METROPOLE TÉLÉVISION', 'MICHELIN', 'MICROPOLE',
                'MODELABS GROUP', 'MONTAIGNE FASHION', 'MONTUPET', 'MR BRICOLAGE',
                'NRJ GROUP', 'NATIXIS', 'NATUREX', 'NEOPOST', 'NETGEM', 'NEURONES',
                'NEXANS', 'NEXITY', 'NICOX', 'NORBERT DENTRESSANGLE',
                'OFI PRIVATE EQUITY CAPITAL', 'OL GROUPE', 'ORAPI', 'OENEO',
                'ORANGE', 'ORCHESTRA - KAZIBAO', 'ORPEA', 'OSIATIS',
                'OUTREMER TELECOM', 'OVERLAP GROUPE', 'OXYMETAL',
                'PSA PEUGEOT CITROËN', 'PSB INDUSTRIES', 'PAGES JAUNES',
                'PAGESJAUNES GROUPE', 'PARROT', 'PARSYS', 'PERNOD RICARD',
                'PHARMAGEST INTER@CTIVE', 'PIERRE & VACANCES', 'PLASTIC OMNIUM',
                'PLASTIVALOIRE', 'PONCIN YACHTS', 'PRISMAFLEX INTERNATIONAL',
                'PRODUITS CHIMIQUES AUXILIAIRES ET DE SYNTHÈSE', 'PROLOGUE',
                'PUBLIC SYSTÈME HOPSCOTCH', 'PUBLICIS', 'PUBLICIS GROUPE',
                'QUANTEL', 'RISC GROUP', 'RECYLEX', 'REMY COINTREAU', 'RENAULT',
                'REXEL', 'RHODIA', 'RIBER', 'RODRIGUEZ GROUP', 'ROUGIER', 'RUBIS',
                'RUE DU COMMERCE', 'RÉMY COINTREAU', 'S.E.B.', 'SEB', 'SES',
                'SIPH', 'SOITEC', 'SPIE', 'ST DUPONT', 'ST MICROELECTRONICS',
                'STMICROELECTRONICS', 'SAFRAN', 'SAFT GROUPE', 'SAINT-GOBAIN',
                'SANOFI', 'SARTORIUS STEDIM BIOTECH', 'SCHNEIDER ELECTRIC',
                'SCOR SE', 'SECHE ENVIRONNEMENT', 'SECHILIENNE - SIDEC', 'SEQUANA',
                'SES FDR', 'SES GLOBAL FDR', 'SILIC', 'SOC MAR TUNNEL PRADO CAR',
                "SOCIETE POUR L'INFORMATIQUE INDUSTRIELLE",
                'SOCIÉTÉ DES AUTOROUTES PARIS - RHIN - RHÔNE', 'SOCIÉTÉ GÉNÉRALE',
                'SODEXO', 'SODITECH INGENIERIE', 'SOFT COMPUTING', 'SOGECLAIR',
                'SOLUCOM', 'SOLVAY', 'SOLVING EFESO INTERNATIONAL', 'SOPRA GROUP',
                'SOPRA STERIA', 'SPIR COMMUNICATION', 'SQLI', 'STALLERGENES',
                'STALLERGÈNES', 'STENTYS', 'STORE ELECTRONIC',
                'SUEZ ENVIRONNEMENT', 'SWORD GROUP', 'SYSTAR', 'SYSTRAN', 'TF1',
                'TARKETT', 'TECHNICOLOR', 'TECHNICOLOR (EX THOMSON)', 'TECHNIPFMC',
                'TELEPERFORMANCE', 'TERREIS', 'TESSI', 'THALES', 'THEOLIA',
                'THERMOCOMPACT', 'TONNA ELECTRONIQUE', 'TOTAL', 'TOUAX',
                'TOUPARGEL GROUPE', 'TRANSGENE', 'TRIGANO', 'U10', 'UBISOFT',
                'UMANIS', 'UNIBAIL-RODAMCO', 'UNION FINANCIÈRE DE FRANCE BQE',
                'UNION TECHNOLOGIES INFORMATIQUE', 'UNIVERSAL MULTIMEDIA', 'VALEO',
                'VALLOUREC', 'VALTECH', 'VEOLIA', 'VEOLIA ENVIRONNEMENT',
                "VET' AFFAIRES", 'VICAT', 'VILMORIN & CIE', 'VINCI', 'VIRBAC',
                'VISIODENT', 'VIVALIS', 'VIVENDI', 'VRANKEN - POMMERY MONOPOLE',
                'WENDEL', 'WORLDLINE', 'XILAM ANIMATION', 'ZODIAC',
                'ZUEBLIN IMMOBILIERE FRANCE', 'ÉLECTRICITÉ ET EAUX DE MADAGASCAR']


ZIP_LIST = [f"{i[0]}{i[1]}{i[2]}{i[3]}0" for i in
            product([1, 2, 3, 4, 5, 6, 7, 8, 9],
                    list(range(10)),
                    list(range(10)),
                    list(range(10)))]


DEPARTEMENT_LIST = ['01 - Ain', '02 - Aisne', '03 - Allier',
                    '04 - Alpes-de-Haute-Provence', '05 - Hautes-Alpes',
                    '06 - Alpes-Maritimes', '07 - Ardèche', '08 - Ardennes',
                    '09 - Ariège', '10 - Aube', '11 - Aude', '12 - Aveyron',
                    '13 - Bouches-du-Rhône', '14 - Calvados', '15 - Cantal',
                    '16 - Charente', '17 - Charente-Maritime', '18 - Cher',
                    '19 - Corrèze', '2A - Corse-du-Sud', '2B - Haute-Corse',
                    "21 - Côte-d'Or", "22 - Côtes-d'Armor", '23 - Creuse',
                    '24 - Dordogne', '25 - Doubs', '26 - Drôme', '27 - Eure',
                    '28 - Eure-et-Loir', '29 - Finistère', '30 - Gard',
                    '31 - Haute-Garonne', '32 - Gers', '33 - Gironde',
                    '34 - Hérault', '35 - Ille-et-Vilaine', '36 - Indre',
                    '37 - Indre-et-Loire', '38 - Isère', '39 - Jura',
                    '40 - Landes', '41 - Loir-et-Cher', '42 - Loire',
                    '43 - Haute-Loire', '44 - Loire-Atlantique', '45 - Loiret',
                    '46 - Lot', '47 - Lot-et-Garonne', '48 - Lozère',
                    '49 - Maine-et-Loire  Note 6', '50 - Manche',
                    '51 - Marne', '52 - Haute-Marne', '53 - Mayenne',
                    '54 - Meurthe-et-Moselle', '55 - Meuse', '56 - Morbihan',
                    '57 - Moselle', '58 - Nièvre', '59 - Nord', '60 - Oise',
                    '61 - Orne', '62 - Pas-de-Calais', '63 - Puy-de-Dôme',
                    '64 - Pyrénées-Atlantiques', '65 - Hautes-Pyrénées',
                    '66 - Pyrénées-Orientales', '67 - Bas-Rhin',
                    '68 - Haut-Rhin', '69 - Rhône', '70 - Haute-Saône',
                    '71 - Saône-et-Loire', '72 - Sarthe', '73 - Savoie',
                    '74 - Haute-Savoie', '75 - Paris', '76 - Seine-Maritime',
                    '77 - Seine-et-Marne', '78 - Yvelines',
                    '79 - Deux-Sèvres', '80 - Somme', '81 - Tarn',
                    '82 - Tarn-et-Garonne', '83 - Var', '84 - Vaucluse',
                    '85 - Vendée', '86 - Vienne', '87 - Haute-Vienne',
                    '88 - Vosges', '89 - Yonne',
                    '90 - Territoire de Belfort', '91 - Essonne',
                    '92 - Hauts-de-Seine', '93 - Seine-Saint-Denis',
                    '94 - Val-de-Marne', "95 - Val-d'Oise", '971 - Guadeloupe',
                    '972 - Martinique', '973 - Guyane', '974 - La Réunion',
                    '976 - Mayotte']


REGION_LIST = ["Auvergne-Rhône-Alpes", "Bourgogne-Franche-Comté",
               "Bretagne", "Centre-Val de Loire", "Corse", "Grand Est",
               "Hauts-de-France", "Île-de-France", "Normandie",
               "Nouvelle-Aquitaine", "Occitanie", "Pays de la Loire",
               "Provence-Alpes-Côte d'Azur", "Guadeloupe", "Martinique",
               "Guyane", "La Réunion", "Mayotte"]
